feat: re-factor Icon component
marshmallow-insurance/smores-react pull request #3326
Opened 2023-12-11 14:22 UTC by rowanhen

## Screenshot / video

N/A

## What does this do?

- implements changes from this doc: https://www.notion.so/getmarshmallow/Refactor-Icon-Implementation-3ab6ed279f154e0ba8caa5ec49771531
- allows us to use SVGs as react components now in our storybook build without any issues
- icons should all stay the same
- allows us to select icons when typing render

2024-01-08 12:27 UTC, DeadEnglish requested changes

2024-01-08 12:27 UTC, DeadEnglish commented on src/Icon/iconsList.ts
> +  windscreen: Windscreen,
I would probably say for consistency we should have these in quotes even though it's not strictly needed.

2024-01-08 12:27 UTC, DeadEnglish commented on src/Icon/iconsTypes.ts
we can remove this entire file in favour of doing the following with `iconsList.ts`:

`export type Icons = keyof typeof iconList`

This would get all the keys of the object and create a type from them, also allows for extensibility and ease of use by simply adding the icon to the list and it'll work!

I can see you're referencing `Icons` within that type so will need some fixing and palying with types. I would probably say we should allow the type to be inferred from the object by removing the `Record<Icons, FC<{ color: Color }>>` type.

2024-01-08 14:00 UTC, rowanhen commented on src/Icon/assets/AccountBreakdown.tsx
> +export const AccountBreakdown: FC = () => {
!!!!! i cant believe i didnt find this / think of this, i did svg { path: ${color} } failed and didnt think to go much further lmao

this fixes it all - will adjust and make these changes now

2024-02-21 15:55 UTC, DeadEnglish approved these changes

2024-02-26 11:55 UTC, merged